package com.vishnu.hotelassistant.service;
import com.vishnu.hotelassistant.dto.BookingRequest; import com.vishnu.hotelassistant.entity.*; import com.vishnu.hotelassistant.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import java.time.temporal.ChronoUnit; import java.util.*;
@Service public class BookingService { private final BookingRepository bookings; private final RoomRepository rooms; private final AppUserRepository users; public BookingService(BookingRepository b,RoomRepository r,AppUserRepository u){bookings=b;rooms=r;users=u;}
 @Transactional public Booking create(String email,BookingRequest req){if(!req.checkOut().isAfter(req.checkIn()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"checkOut must be after checkIn"); Room room=rooms.findById(req.roomId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Room not found")); if(!room.isAvailable())throw new ResponseStatusException(HttpStatus.CONFLICT,"Room is not available"); AppUser user=users.findByEmail(email).orElseThrow(); long nights=ChronoUnit.DAYS.between(req.checkIn(),req.checkOut()); Booking b=Booking.builder().bookingNumber("HTL-"+UUID.randomUUID().toString().substring(0,8).toUpperCase()).user(user).room(room).checkIn(req.checkIn()).checkOut(req.checkOut()).status(BookingStatus.CONFIRMED).totalAmount(nights*room.getPricePerNight()).build(); return bookings.save(b);}
 public List<Booking> mine(String email){return bookings.findByUserEmailOrderByCheckInDesc(email);}
 public Booking findForUser(String number,String email){return bookings.findByBookingNumberAndUserEmail(number,email).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Booking not found"));}
 @Transactional public Booking cancelForUser(String number,String email){Booking b=findForUser(number,email); if(b.getStatus()==BookingStatus.CANCELLED)return b; b.setStatus(BookingStatus.CANCELLED); return bookings.save(b);}
 public List<Booking> all(){return bookings.findAll();}
}
